### ISSUE TITLE
lazy: false is not working

### ISSUE THREAD

**Issue by PredokMiF** [shellscape/koa-webpack#21]
When I setup `lazy` prop to `false`, it is stop working correct: webpack build bundle, but return error with 404 status

**Comment by shellscape** [comment]
Please start reporting issues with relevant information (this is a practice you should always use when reporting issues anywhere)

Node version:
NPM version:
Koa version:
koa-webpack version:

Code causing the error:

Error output:

**Comment by PredokMiF** [comment]
Sorry, next time I will attach this information immediately
```
OS: Win10Pro
node@7.4.0
npm@4.0.5
koa@2.0.0
koa-webpack@0.2.0
```
Project to fast try it https://github.com/PredokMiF/koa-webpack-example
Change in `app.js` code `.use(devWare({config, dev:{lazy:true}, hot:{}}))`

On request:
```
webpack building...
webpack: wait until bundle finished: /bundle.js
webpack built 17e00f73cfb004a24690 in 1603ms
_http_outgoing.js:367
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:367:11)
    at Object.set (C:\src\nodejs\koa-webpack-example\node_modules\koa\lib\response.js:437:16)
    at Object.proto.(anonymous function) [as set] (C:\src\nodejs\koa-webpack-example\node_modules\delegates\index.js:40:31)
    at Object.handleRangeHeaders (C:\src\nodejs\koa-webpack-example\node_modules\webpack-dev-middleware\lib\Shared.js:55:8)
    at processRequest (C:\src\nodejs\koa-webpack-example\node_modules\webpack-dev-middleware\middleware.js:63:21)
    at continueBecauseBundleAvailable (C:\src\nodejs\koa-webpack-example\node_modules\webpack-dev-middleware\lib\Shared.js:116:6)
    at Array.forEach (native)
    at C:\src\nodejs\koa-webpack-example\node_modules\webpack-dev-middleware\lib\Shared.js:115:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Hash: 17e00f73cfb004a24690
Version: webpack 2.2.0
Time: 1603ms
    Asset     Size  Chunks             Chunk Names
bundle.js  3.15 kB       0  [emitted]  main
chunk    {0} bundle.js (main) 141 bytes [entry] [rendered]
    [0] ./src/app.js 37 bytes {0} [built]
    [1] ./src/foo.js 76 bytes {0} [built]
    [2] multi ./app.js 28 bytes {0} [built]
webpack: bundle is now VALID.

Process finished with exit code 1
```

**Comment by shellscape** [comment]
We previously triaged and solved that error here: https://github.com/shellscape/koa-webpack/issues/2

If it's still not working for your implementation, we'd happily accept a PR to fix it.
