### ISSUE TITLE
TypeError: webpack-hot-client: `entry` Object values must be an Array. 

### ISSUE THREAD

**Issue by mrchief** [shellscape/koa-webpack#80]
The latest uses this `"webpack-hot-client": "^1.0.1"` which is over 2 years old. It produces this error which is due to buggy code in 1.0.1

```
TypeError: webpack-hot-client: `entry` Object values must be an Array. Please check your webpack config.
        at validateEntry (D:\myapp\node_modules\webpack-hot-client\lib\util.js:138:19)
        at module.exports (D:\myapp\node_modules\webpack-hot-client\index.js:26:3)
        at fn (D:\myapp\node_modules\koa-webpack\index.js:74:18)
```

My entry object:

```
 entry: [
    'babel-polyfill', // Support promise for IE browser (for dev)
    'react-hot-loader/patch',
    'webpack-hot-middleware/client?reload=true',
    './src/client.js'
  ]
```

In the latest webpack-hot-client, this check has been fixed.

**Comment by mrchief** [comment]
The same code was working fine with `koa-webpack: ^1.0.0`

**Comment by mrchief** [comment]
Sorry, I messed up. This is an issue for webpack-hot-client it seems.

**Comment by mrchief** [comment]
Created https://github.com/webpack-contrib/webpack-hot-client/issues/11
