### ISSUE TITLE
The hook "failed" does not exist on a MultiCompiler

### ISSUE THREAD

**Issue by mike-marcacci** [shellscape/koa-webpack#87]
Thanks for the super helpful project!

* Node Version: 9.6.1
* koa Version: 2.5.0
* koa-wepback Version: 3.0.1
* webpack Version: 4.1.1

It appears that koa-webpack does not wait for the build to finish **using Webpack 4** (probably due to new async rendering stuff). When a change is made, but before it has finished compiling, a request to the server ends with a 500 and the following in the logs:

```
  TypeError: Cannot read property 'tap' of undefined
      at Promise (/Users/mike/Code/boltline/app/node_modules/koa-webpack/index.js:24:29)
      at new Promise (<anonymous>)
      at waitMiddleware (/Users/mike/Code/boltline/app/node_modules/koa-webpack/index.js:19:12)
      at /Users/mike/Code/boltline/app/node_modules/koa-webpack/index.js:31:5
      at app.use (/Users/mike/Code/boltline/app/server.development.js:31:10)
      at dispatch (/Users/mike/Code/boltline/app/node_modules/koa-compose/index.js:42:32)
      at /Users/mike/Code/boltline/app/node_modules/koa-compose/index.js:34:12
      at Application.handleRequest (/Users/mike/Code/boltline/app/node_modules/koa/lib/application.js:150:12)
      at handleRequest (/Users/mike/Code/boltline/app/node_modules/koa/lib/application.js:132:19)
      at Server.proxy (/Users/mike/Code/boltline/app/server/addProxy.js:33:9)
      at Server.emit (events.js:127:13)
      at parserOnIncoming (_http_server.js:642:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
```

Once the build finishes, everything continues as expected. This began after upgrading to webpack 4.

```es6
// webpack.config.js
module.exports = [
  {
    // ...any valid config
  },
  {
    // ...any valid config
  }
];
```

**Comment by mike-marcacci** [comment]
My apologies for the omissions! The issue ended up being that a `MultiCompiler` doesn't have a "failed" hook. PR #88 adds a test and fix, following [webpack-dev-server](https://github.com/webpack/webpack-dev-server/commit/c375aa6f33ea5c2dafea914e38c8160d93136727). Let me know if there's anything else you need me to provide.
